version: "3.8"

services:
    app: 
        image: node:16-alpine
        command: sh -c "yarn && yarn build && yarn start"
        ports: 
            - 5500:5500
        working_dir: /app
        volumes: 
            - ./:/app
        environment: 
            test: test
